config/routes.rb
Rails.application.routes.draw do
  resources :members
  root 'dashboard#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb

class Match < ApplicationRecord
	has_many :match_members
	has_many :members,through: :match_members
end

app/models/match_member.rb
class MatchMember < ApplicationRecord
	enum result: [:loose,:win]

	belongs_to :match
	belongs_to :member

	after_save :calculate_average_score

	def calculate_average_score
		average_score = member.match_members.average(:score).round(2)
		self.member.update_attribute(:average_score,average_score)
	end
end

app/models/member.rb
class Member < ApplicationRecord	
  validates :name,:joining_date,:phone_number, presence: true
  validates :phone_number, uniqueness: true

	has_many :match_members
	has_many :matches,through: :match_members

	scope :top_10_participant, -> { joins(:match_members).group('members.id').having('count(match_members.id) >= 10').order("members.average_score desc").limit(10) }

	def get_number_of_wins
		match_members.where(result: 1).count
	end

	def get_number_of_losses
		match_members.where(result: 0).count
	end

	def get_highest_score
		match_member = match_members.order("score DESC").first
		result = Hash.new
		if match_member
			match = match_member.match
			opponent = nil
			match.match_members.map {|mm| opponent = mm.member if mm.member_id != self.id}
			result = { location: match.location, held: match.held,score: match_member.score,name: opponent.name }
		end
		result
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@top_participants = Member.top_10_participant
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name,:joining_date,:phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/dashboard/index.html.erb
<% @top_participants.each do |participant| %>
  <div class="col-md-4">
    <div class="card mb-4 shadow-sm">
      <div class="card-header"><%= participant.name %></div>
      <div class="card-body">
        <p class="card-text">Average Score:: <%= participant.average_score %></p>
      </div>
      <div class="card-footer">
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <%= link_to "View", member_path(participant.id) ,class: "btn btn-sm btn-outline-secondary" %>
            <%= link_to "Edit", edit_member_path(participant.id) ,class: "btn btn-sm btn-outline-secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end if @top_participants %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrabbleClubChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <%= render :partial => "shared/header" %>
    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <label for="email">Name:</label>
      <%= form.text_field :name,class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="pwd">Joining Date:</label>
      <%= form.date_field :joining_date,class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="email">Phone Number:</label>
      <%= form.text_field :phone_number,class: "form-control" %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Joining Date</th>
      <th>Average Score</th>
      <th>Phone Number</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.joining_date %></td>
        <td><%= member.average_score %></td>
        <td><%= member.phone_number %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<% highest_score_detail = @member.get_highest_score %>
<div class="col-md-9">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-12 lead">Member Profile<hr></div>
      </div>
      <div class="row">
				<div class="col-md-4 text-center">
          <img class="img-circle avatar avatar-original" style="-webkit-user-select:none; 
          display:block; margin:auto;" src="http://robohash.org/sitsequiquia.png?size=120x120">
        </div>
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-12">
              <h1 class="only-bottom-margin"><%= @member.name %></h1>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <span class="text-muted">Joining Date:</span> <%= @member.joining_date %><br>
              <span class="text-muted">Phone Number:</span> <%= @member.phone_number %><br>
              <span class="text-muted">Number of Wins:</span> <%= @member.get_number_of_wins %><br>
              <span class="text-muted">Number of Losses:</span> <%= @member.get_number_of_losses %><br>
              <span class="text-muted">Average Score:</span> <%= @member.average_score %><br>
              <span class="text-muted">Highest Score:</span> <%= highest_score_detail[:score] || "-" %><br>
              <span class="text-muted">Match Location:</span> <%= highest_score_detail[:location] %><br>
              <span class="text-muted">Match Date:</span> <%= highest_score_detail[:held] %><br>
              <span class="text-muted">Opponent Name:</span> <%= highest_score_detail[:name] %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <hr>
          <button class="btn btn-default pull-right"><i class="glyphicon glyphicon-pencil"></i> <%= link_to 'Edit', edit_member_path(@member) %></button>
          <button class="btn btn-default pull-right"><i class="glyphicon glyphicon-pencil"></i> <%= link_to 'Back', members_path %></button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header style="padding-top: 25px;">
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Scrabble Club</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if params[:controller] == 'dashboard' %>">
          <a class="nav-link" href="<%= root_path %>">Dashboard <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item <%= 'active' if params[:controller] == 'members' %>">
          <a class="nav-link" href="<%= members_path %>">Members</a>
        </li>
      </ul>
    </div>
  </nav>
</header>